updated files
sakshisubedi/house-renting-application pull request #34
Opened 2023-03-08 05:52 UTC by pratyush82

Following changes were made : 

- Design updates on the individual listing page including in list of interested people modals
- integrated rating APIs in the individual listing page
- commented Rent/Lease button on landing page
- fixed routing of listing to its corresponding individual listing page
- clicking on profile now routes to corresponding logged in user profile page

2023-03-08 06:07 UTC, sakshisubedi commented
@pratyush82 
Add rating is not working as `listingId` is not passed in the API
<img width="649" alt="Screenshot 2023-03-07 at 10 05 30 PM" src="https://user-images.githubusercontent.com/35215747/223632846-6a7dd9cb-0480-42a2-af65-8a649de55c85.png">

2023-03-08 06:08 UTC, sakshisubedi approved these changes

2023-03-08 06:09 UTC, sakshisubedi requested changes
Check for add rating

2023-03-08 06:25 UTC, pratyush82 commented
> Check for add rating

might have fixed the bug

2023-03-08 07:36 UTC, mounikapadala11 approved these changes

2023-03-08 08:08 UTC, Harrishee approved these changes

2023-03-09 02:26 UTC, stephaniekwan approved these changes

2023-03-09 16:00 UTC, merged