User Authentication Client
sakshisubedi/house-renting-application pull request #36
Opened 2023-03-08 09:05 UTC by Harrishee

Fix the auth issues and add pop window for the navbar

2023-03-08 15:13 UTC, sakshisubedi requested changes

2023-03-08 15:13 UTC, sakshisubedi commented on client/src/Components/NavBar.js
> +    Avatar,
run `npm run build` before pushing your changes.

2023-03-09 00:11 UTC, pratyush82 approved these changes

2023-03-09 02:19 UTC, JinHammer approved these changes

2023-03-09 06:02 UTC, closed without merging