Feature: User API
sakshisubedi/house-renting-application pull request #6
Opened 2023-02-21 04:12 UTC by stephaniekwan

2023-02-21 04:18 UTC, sakshisubedi requested changes

2023-02-21 04:18 UTC, sakshisubedi commented on server/controllers/user.js
> +                data: await models.user.find().select({ __v: 0 })
@stephaniekwan I think we should skip sending passwords in the response. Similarly in getUserByID.

2023-02-21 04:18 UTC, sakshisubedi commented on server/controllers/user.js
> +                data: await models.user.findById(req.params.id).select({ __v: 0 })
Also, you might need an additional/reuse API to fetch users by id which restricts the private field in the response.
(This feature is required when the user wants to view another user's profile.)

2023-02-21 16:40 UTC, sakshisubedi commented on server/controllers/user.js
> +                data: await models.user.findByIdAndUpdate(req.params.id, req.body, {new: true})
While updating the user you won't get all the fields like `password`, so initially, you might want to fetch the user obj, merge them and update it.

2023-02-22 17:06 UTC, sakshisubedi requested changes

2023-02-22 17:06 UTC, sakshisubedi commented on server/controllers/user.js
> +            if (!user.email.isPublic) {
@stephaniekwan, instead of deleting, you can make a filter query to skip those fields

2023-02-23 00:02 UTC, stephaniekwan commented on server/controllers/user.js
> +            if (!user.email.isPublic) {
@sakshisubedi , since not all the fields have an isPublic attribute, I wasn't sure if there would be a simple way to do this. Shouldn't this be fine though since I'm not deleting anything from the db, its just deleting from the temporary json object

2023-02-26 07:17 UTC, pratyush82 approved these changes

2023-02-26 18:53 UTC, Harrishee approved these changes

2023-02-28 01:55 UTC, JinHammer approved these changes

2023-02-28 02:35 UTC, merged